version: '3'

services:

  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    networks:
      - struck

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - '1111:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - struck

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    ports:
      - '2222:80'
    volumes:
      - wp_data:/var/www/html/wp-content
      - .:/var/www/html/wp-content/plugins/struck
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    networks:
      - struck

networks:
  struck:

volumes:
  db_data:
  wp_data:
